# Generated by Django 5.2.13 on 2026-04-28 20:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('sms', 'SMS')], max_length=20)),
                ('contato', models.CharField(max_length=200)),
                ('ordem_envio', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('enviada', models.BooleanField(default=False)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='core.destinatario')),
            ],
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='midias/%Y/%m/')),
                ('tipo', models.CharField(max_length=10)),
                ('hash_arquivo', models.CharField(max_length=64, unique=True)),
                ('tamanho_bytes', models.IntegerField()),
                ('largura', models.IntegerField(blank=True, null=True)),
                ('altura', models.IntegerField(blank=True, null=True)),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='core.mensagem')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_sinal_vida', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('suspeito', 'Suspeito (sem resposta)'), ('falecido', 'Falecido - aguardando envio'), ('enviado', 'Mensagens enviadas')], default='ativo', max_length=20)),
                ('tempo_resposta_dias', models.IntegerField(default=30)),
                ('dias_tolerancia', models.IntegerField(default=7)),
                ('curador_nome', models.CharField(blank=True, max_length=200)),
                ('curador_email', models.EmailField(blank=True, max_length=254)),
                ('curador_telefone', models.CharField(blank=True, max_length=20)),
                ('curador_codigo', models.CharField(blank=True, max_length=64, unique=True)),
                ('plano', models.CharField(default='gratuito', max_length=20)),
                ('data_assinatura', models.DateTimeField(blank=True, null=True)),
                ('data_expiracao', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100)),
                ('detalhes', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.perfil')),
            ],
        ),
        migrations.AddField(
            model_name='destinatario',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='core.perfil'),
        ),
    ]
