# Generated by Django 5.2.13 on 2026-06-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/', verbose_name='Foto de perfil'),
        ),
    ]
