# Generated by Django 5.2.13 on 2026-06-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfil_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nome do Serviço')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('emoji', models.CharField(default='⭐', max_length=10, verbose_name='Ícone/Emoji')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Serviços Extras',
            },
        ),
    ]
